# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 机场签到

on:
  # push:
  #   branches: main
  # gollum:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run
      env:
        web: ${{ secrets.AIRPORT_WEB }}
        user: ${{ secrets.AIRPORT_USER }}
        pwd: ${{ secrets.AIRPORT_PWD }}
        sckey: ${{ secrets.SEND_KEY }}
        ktkey: ${{ secrets.KTKEY }}
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        python3 checkin_airport.py
